spring:
  debug: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
          format_sql: true
          ddl-auto: update

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

app:
  jwt_secret: ${JWT_SECRET}
